const iconImages = {
    '1': require('./images/1-s.png'),
    '2': require('./images/2-s.png'),
    '3': require('./images/3-s.png'),
    '4': require('./images/4-s.png'),
    '5': require('./images/5-s.png'),
    '6': require('./images/6-s.png'),
    '7': require('./images/7-s.png'),
    '8': require('./images/8-s.png'),
    '11': require('./images/11-s.png'),
    '12': require('./images/12-s.png'),
    '13': require('./images/13-s.png'),
    '14': require('./images/14-s.png'),
    '15': require('./images/15-s.png'),
    '16': require('./images/16-s.png'),
    '17': require('./images/17-s.png'),
    '18': require('./images/18-s.png'),
    '19': require('./images/19-s.png'),
    '20': require('./images/20-s.png'),
    '21': require('./images/21-s.png'),
    '22': require('./images/22-s.png'),
    '23': require('./images/23-s.png'),
    '24': require('./images/24-s.png'),
    '25': require('./images/25-s.png'),
    '26': require('./images/26-s.png'),
    '29': require('./images/29-s.png'),
    '30': require('./images/30-s.png'),
    '31': require('./images/31-s.png'),
    '32': require('./images/32-s.png'),
    '33': require('./images/33-s.png'),
    '34': require('./images/34-s.png'),
    '35': require('./images/35-s.png'),
    '36': require('./images/36-s.png'),
    '37': require('./images/37-s.png'),
    '38': require('./images/38-s.png'),
    '39': require('./images/39-s.png'),
    '40': require('./images/40-s.png'),
    '41': require('./images/41-s.png'),
    '42': require('./images/42-s.png'),
    '43': require('./images/43-s.png'),
    '44': require('./images/44-s.png'),
}

const theme1 = {
    mainBackground: '#B2F3E8',
    titles: 'black',
    subtitles: 'gray',
    activeButton: '#3D6290',
    inactiveButton: '#B9CDE2',
    searchBar: 'gray',
    mainTemperature: '#50B2AF',
    borders: 'gray',
    favoritesBottomBackground: '#B2F3E8',
    favoritesButton: '#3D6290',
    favoritesBackground: 'white'
}

const theme2 = {
    mainBackground: '#202020',
    titles: 'white',
    subtitles: 'gray',
    activeButton: 'white',
    inactiveButton: '#595959',
    searchBar: 'gray',
    mainTemperature: '#F3BFBF',
    borders: 'gray',
    favoritesBottomBackground: '#3B3B3B',
    favoritesButton: 'white',
    favoritesBackground: '#202020'

}

export { iconImages, theme1, theme2 }